spring:
  datasource:
    druid:
      url: jdbc:postgresql://localhost:5432/hrims?currentSchema=hrims
      username: hrims
      password: hrims_Kk6neiid
      driver-class-name: org.postgresql.Driver
      # 连接池初始化大小
      initial-size: 3
      # 最大活跃数
      max-active: 10
      # 最大等待
      max-wait: 5
      # 最小空闲
      min-idle: 1
      # 查询超时, ms
      query-timeout: 60000

# Mybatis-plus 相关配置
mybatis-plus:
  mapper-locations: classpath:mappers/*Mapper.xml

# minio配置
minio:
  url: http://localhost:9000
  accessKey: hrims
  secretKey: passw0rd
  bucket: hrims

# 是否开启swagger
swagger:
  enabled: true